config/routes.rb
Rails.application.routes.draw do
  resources :buyers
  resources :gas

  post '/purchase_gas' => 'gas#purchase'
  get '/reports' => 'gas#reports'

  root to: "gas#dashboard"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gas.rb
class Gas < ActiveRecord::Base
	has_many :gas_volumes, :dependent => :destroy

	validates_presence_of :gas_type
	validates :price, numericality: { less_than_or_equal_to: 999999, greater_than_or_equal_to: 0 }

	LOYALTY_CARD = ["SM Advantage", "Robinsons Rewards"]

	def self.loyalty_cards
		LOYALTY_CARD
	end
end

app/controllers/gas_controller.rb
class GasController < ApplicationController
  before_action :set_gas, only: %i[ show edit update destroy ]
  before_action :get_purchase_history, only: %i[ dashboard ]
  before_action :set_type, only: %i[ reports ]

  # GET /gas or /gas.json
  def index
    @gas = Gas.select('gas.*, gas_volumes.remaining_volume').joins(:gas_volumes).all || []
  end

  def dashboard
    @gas = Gas.select('gas.*, gas_volumes.remaining_volume, gas_volumes.id as volume_id').joins(:gas_volumes).where.not(gas_volumes: {remaining_volume: 0}).group(:gas_id).all || []
    @buyers = Buyer.all || []
    @last_buyer = PurchaseHistory.last.buyer_id
  end

  # GET /gas/1 or /gas/1.json
  def show
  end

  # GET /gas/new
  def new
    @gas = Gas.new
  end

  # GET /gas/1/edit
  def edit
  end

  # POST /gas or /gas.json
  def create
    @gas = Gas.new(gas_params)
    remaining_volume = params[:gas][:remaining_volume].present? ? params[:gas][:remaining_volume] : GasVolume::INITIAL_VOLUME
    @gas_volume = @gas.gas_volumes.build(total_volume: GasVolume::GAS_TANK_CAPACITY, remaining_volume: remaining_volume)

    respond_to do |format|
      if @gas.save
        format.html { redirect_to gas_url(@gas), notice: "Gas was successfully created." }
        format.json { render :show, status: :created, location: @gas }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gas.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gas/1 or /gas/1.json
  def update
    respond_to do |format|
      if @gas.update(gas_params)
        remaining_volume = params[:gas][:remaining_volume].present? ? params[:gas][:remaining_volume] : GasVolume::INITIAL_VOLUME

        if @gas.gas_volumes.last.remaining_volume > 0
          @gas.gas_volumes.last.update_attributes(remaining_volume: remaining_volume)
        else
          @gas_volume = @gas.gas_volumes.build(total_volume: GasVolume::GAS_TANK_CAPACITY, remaining_volume: remaining_volume)
          @gas_volume.save
        end
        
        format.html { redirect_to gas_url(@gas), notice: "Gas was successfully updated." }
        format.json { render :show, status: :ok, location: @gas }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gas.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gas/1 or /gas/1.json
  def destroy
    @gas.destroy

    respond_to do |format|
      format.html { redirect_to gas_index_url, notice: "Gas was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def purchase
    gas_ids = params[:gas]&.keys

    @gas_volumes = GasVolume.where(id: gas_ids).where.not(remaining_volume: 0).group(:gas_id)

    respond_to do |format|
      @gas_volumes.each_with_index do |gas, index|
        remaining_volume = gas.remaining_volume
        volume_to_purchase = params[:gas].values[index].to_i

        @purchase_history = PurchaseHistory.new

          if volume_to_purchase.to_i > 0
              if remaining_volume >= volume_to_purchase
                gas.update_attributes!(remaining_volume: remaining_volume - volume_to_purchase)

                @purchase_history.gas_volume = gas
                @purchase_history.buyer_id = params[:buyer_id]
                @purchase_history.total_pay = params[:total_gas_pay]
                @purchase_history.total_discount = params[:total_gas_discount]
                @purchase_history.liters_bought = params[:gas].values[index]
                @purchase_history.with_loyalty = 1 if params[:loyalty_card].present?
                @purchase_history.save!

                format.html { redirect_to root_path, notice: "Gas purchased successfully." }
                format.json { render :dashboard, status: :created }
              else
                gas = GasVolume.select('gas.gas_type').joins(:gas).where(params[:gas].keys[index]).first
                format.html { redirect_to root_path, notice: "Insufficient Purchase. Remaining Volume for #{gas.gas_type} is #{remaining_volume} Liters" }
                format.json { head :no_content }
              end
          end
       end 
    else
      format.html { redirect_to root_path, notice: "Invalid Purchase." }
      format.json { head :no_content }
    end
  end

  def reports
    if @type == "complete_purchase"
      get_purchase_history
    else
      @purchase_histories = PurchaseHistory.select('*').joins(:gas_volume, :buyer, :gas).where.not(with_loyalty: 0).order(id: :desc) || []
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gas
      @gas = Gas.select('gas.*, gas_volumes.remaining_volume').joins(:gas_volumes).where(gas: {id: params[:id]}).order("gas_volumes.remaining_volume desc").first || []
    end

    def get_purchase_history
      @purchase_histories = PurchaseHistory.select('*').joins(:gas_volume, :buyer, :gas).order(id: :desc) || []
    end

    def set_type
      @type = if params[:type] != "complete_purchase"
        "loyalty_buyer"
      else
        "complete_purchase"
      end
    end
    # Only allow a list of trusted parameters through.
    def gas_params
      params.require(:gas).permit(:gas_type, :price, :price)
    end
end

app/helpers/gas_helper.rb
module GasHelper
end

app/views/gas/_first_box.html.erb
  <div class="container first-box">
    <div style="display: flex;flex-direction: column;justify-content: space-between; height: 100%;">
      <div>
        <%= link_to 'Gas', gas_index_path, class: 'button menu-link' %>
        <%= link_to 'Buyers', buyers_path, class: 'button menu-link' %>
        <%= link_to 'Reports', reports_path(type: "complete_purchase"), class: 'button menu-link' %>
      </div>

      <div>
        <br>
        <h2>Buyer Name:</h2>
        <div class="field">
          <%= select_tag "Buyers Available", options_for_select(@buyers.map {|buyer| [buyer.name, buyer.id, {'data-loyalty_card' => buyer.loyalty_card }]}, @last_buyer), {class: 'no-margin-btm', name: "buyer", disabled: @buyers.blank?, id: "current_buyer", onchange: "leaveChange()"}  %>

        </div>
      </div>
    </div>

  </div>

app/views/gas/_form.html.erb
<div class="container">
  <%= form_with(model: gas, local: true) do |form| %>
    <% if gas.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(gas.errors.count, "error") %> prohibited this gas from being saved:</h2>

        <ul>
        <% gas.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :gas_type %>
      <%= form.text_field :gas_type, id: :gas_gas_type %>
    </div>

    <div class="field">
      <%= form.label :price %>
      <%= form.text_field :price, id: :gas_price %>
    </div>

    <div class="field">
      <%= form.label :remaining_volume %>
      <%= form.text_field :remaining_volume, id: :gas_remaining_volume %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

</div>

app/views/gas/_last_box.html.erb
  <div class="container last-box">
    <div style="display: flex;">
      <h1>Gas Left: <%= @gas.present? ? total_gas_remaining(@gas.pluck(:remaining_volume).compact) : 0%>%</h1>
    </div>
    <br/>
    <% @gas.each do |gas| %>
      <div style="display: flex;">
        <div class="gas_initial" style="width: 40px; height: 40px; font-size: 2rem;"><%=gas.gas_type[0].titleize%></div>
        <h2 class="margin-x"><%=gas.gas_type%>:&nbsp;</h2>
        <h2><%=remaining_gas_percentage(gas.remaining_volume)%> L</h2>
      </div>
      <br />
    <%end%>

    <div>
      <hr>
      <br />
      <h3>Recent Purchase History</h3>
      <table>
        <thead>
          <tr>
            <th>Buyer</th>
            <th>Gas Type</th>
            <th>Total Pay</th>
            <th>Total Discount</th>
            <th>Liters Bought</th>
          </tr>
        </thead>

        <tbody>
          <% @purchase_histories.limit(4).each do |purchase_history| %>
            <tr>
              <td><%= purchase_history.name %></td>
              <td><%= purchase_history.gas_type %></td>
              <td>Php <%= purchase_history.total_pay %></td>
              <td>Php <%= purchase_history.total_discount || 0 %></td>
              <td><%= purchase_history.liters_bought %> L</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/gas/_middle_box.html.erb
  <div class="container middle-box">
    <%= form_tag(purchase_gas_path, method: "post", local: true) do %>
    <%=hidden_field_tag :buyer_id%>
    <%=hidden_field_tag :loyalty_card%>
    <%=hidden_field_tag :total_gas_pay%>
    <%=hidden_field_tag :total_gas_discount%>
    <%=hidden_field_tag :total_liters_bought%>

    <% gas_list.each do |gas| %>
    <div class="card">
      <div style="display: flex;">
        <div class="gas_initial"><%=gas.gas_type[0].titleize%></div>
        <div class="margin-x" style="width: 120px;">
          <h1><%=gas.price%> / L</h1>
          <h2 class="price"><%=gas.gas_type%></h2>
        </div>

        <div>
          <%= number_field_tag "gas[#{gas.volume_id}]", "", min: 0, class: "gas_input_field", onchange: "calculate_total_pay()", onmouseout: "calculate_total_pay()", data: {price: gas.price, gas: gas.gas_type}%>
        </div>
      </div>
    </div>
    <br />
    <%end%>

    <hr>

    <div style="display: flex; justify-content: space-between;">
      <h3>Total Pay:</h3>
      <h3>Php <span id="total_pay">1231.1</span></h3>
    </div>

    <div style="display: flex; justify-content: space-between;">
      <h3>Discount:</h3>
      <h3>Php <span id="discount">1231.1</span></h3>
    </div>

    <hr>
    <br>
    <div style="display: flex; justify-content: space-between;">
      <%= submit_tag("Confirm", disabled: @gas.blank?) %>

      <a class="button" onclick="clearFields()" style="margin-top: 0 !important; padding-top: 8px;">Clear</a>
    </div>

    <%end%>
  </div>

  <script type="text/javascript">
    var current_buyer = document.getElementById("current_buyer");
    var loyalty_card = document.getElementById("loyalty_card")
    function leaveChange() {
        document.getElementById("buyer_id").value = current_buyer.value;
        var buyer_selected = current_buyer.options[current_buyer.selectedIndex];
        loyalty_card.value = buyer_selected.dataset.loyalty_card;
        calculate_total_pay();
    }
    current_buyer.onchange();

    function calculate_total_pay() {
       var total_pay = total_price = total_discount = total_liters_bought = 0;
        var input = document.getElementsByClassName("gas_input_field");

        for (var i = 0; i < input.length; i++) {
            var litter_of_gas_purchased = input[i];
            var price_per_litter = input[i].dataset.price;
            var gas_type = input[i].dataset.gas;

            if (litter_of_gas_purchased.value !== "" && litter_of_gas_purchased.value != 0) {
              total_price = parseFloat(litter_of_gas_purchased.value) * parseFloat(price_per_litter);
              total_liters_bought = total_liters_bought + parseFloat(litter_of_gas_purchased.value)
              if (loyalty_card.value !== "" && gas_type.toLowerCase() == "diesel") {
                var discount = (20 * total_price) / 100;
                total_pay = total_pay + (total_price - discount);
                total_discount = total_discount + discount;
              }
              else if (loyalty_card.value !== "") {
                var discount = (10 * total_price) / 100;
                total_pay = total_pay + (total_price - discount);
                total_discount = total_discount + discount;
              } else {
                total_pay = total_pay + total_price;
                total_discount = total_discount + 0;
              }

            };
        }

        document.getElementById("total_pay").innerText = parseFloat(total_pay).toFixed(2);
        document.getElementById("discount").innerText = parseFloat(total_discount).toFixed(2);
        document.getElementById("total_gas_pay").value = parseFloat(total_pay).toFixed(2);
        document.getElementById("total_gas_discount").value = parseFloat(total_discount).toFixed(2);
        document.getElementById("total_liters_bought").value = parseFloat(total_liters_bought).toFixed(2);
    }

    function clearFields() {
      var input = document.getElementsByClassName("gas_input_field");

      for (var i = 0; i < input.length; i++) {
        input[i].value = "";
      }
    }
  </script>

app/views/gas/dashboard.html.erb
<p id="notice"><%= notice %></p>

<div style="display: flex;">
  <%= render 'first_box', gas_list: @gas %>

  <%= render 'middle_box', gas_list: @gas %>

  <%= render 'last_box', gas_list: @gas %>
</div>

app/views/gas/edit.html.erb
<h1>Editing Gas with ID: <%=@gas.id%></h1>

<%= render 'form', gas: @gas %>

<%= link_to '❮ Back', gas_path, class: "button" %>

app/views/gas/index.html.erb
<p id="notice"><%= notice %></p>

<div style="display: flex; justify-content: space-between; align-items: baseline;">
  <h1>Gas</h1>
  <%= link_to '❮ Dashboard', root_path, class: "button" %>
</div>

<table>
  <thead>
    <tr>
      <th>Gas type</th>
      <th>Price</th>
      <th>Remaining Volume</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gas.each do |gas| %>
      <tr>
        <td><%= gas.gas_type %></td>
        <td><%= gas.price %></td>
        <td><%= gas.remaining_volume || 0 %> Liters / <%=GasVolume::GAS_TANK_CAPACITY%> Liters</td>
        <td><%= link_to 'Show', gas %></td>
        <td><%= link_to 'Edit', edit_gas_path(gas) %></td>
        <td><%= link_to 'Delete', gas, method: :delete, data: { confirm: "Are you sure to delete #{gas.gas_type}?\nThis will also delete all purchase history for this record." } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '+ New Gas', new_gas_path, class: "button" %>

app/views/gas/new.html.erb
<h1>New Gas</h1>

<%= render 'form', gas: @gas %>

<%= link_to '❮ Back', gas_index_path, class: "button" %>

app/views/gas/reports.html.erb
<div class="container">
	<div>
	  <div style="display: flex; justify-content: space-between; align-items: baseline;">
	    <h1><%=reports_helper(@type)%></h1>
	    <%= link_to '❮ Dashboard', root_path, class: "button" %>
	  </div>
	  <%= link_to 'Complete Purchase History', reports_path(type: "complete_purchase") %> |
	  <%= link_to 'Loyalty Buyer Transcation History', reports_path(type: "loyalty_buyer") %>
	  <table>
	    <thead>
	      <tr>
	        <th>Buyer</th>
	        <th>Gas Type</th>
	        <th>Total Pay</th>
	        <th>Total Discount</th>
	        <th>Liters Bought</th>
	      </tr>
	    </thead>

	    <%if @purchase_histories.present?%>
	    <tbody>
	      <% @purchase_histories.each do |purchase_history| %>
	        <tr>
	          <td><%= purchase_history.name %></td>
	          <td><%= purchase_history.gas_type %></td>
	          <td>Php <%= purchase_history.total_pay %></td>
	          <td>Php <%= purchase_history.total_discount || 0 %></td>
	          <td><%= purchase_history.liters_bought %> L</td>
	        </tr>
	      <% end %>
	      <tr style="border-top: 2px solid #003a6c;">
	      	<td></td>
	      	<td></td>
	      	<td>Php <%=@purchase_histories.pluck(:total_pay).inject(0, :+).to_f%></td>
	      	<td>Php <%=@purchase_histories.pluck(:total_discount).inject(0, :+).to_f%></td>
	      	<td><%=@purchase_histories.pluck(:liters_bought).inject(0, :+).to_f%> L</td>
	      </tr>
	    </tbody>
	    <%end%>
	  </table>
	</div>
</div>

app/views/gas/show.html.erb
<h1>Gas with ID: <%=@gas.id%></h1>

<p id="notice"><%= notice %></p>

<div class="container">
    <div class="field">
      <%= label_tag :gas_type %>
      <%= text_field_tag :gas_type, @gas.gas_type, disabled: true %>
    </div>

    <div class="field">
      <%= label_tag :price %>
      <%= number_field_tag :price, @gas.price, min: 0, class: "gas_input_field", disabled: true%>
    </div>

    <div class="field">
      <%= label_tag :remaining_volume %>
      <%= number_field_tag :remaining_volume, @gas.remaining_volume, min: 0, class: "gas_input_field", disabled: true%>
    </div>

    <%= link_to 'Edit', edit_gas_path(@gas), class: 'button' %>
</div>

<br>

<%= link_to '❮ Back', gas_index_path, class: "button" %>