config/routes.rb
Rails.application.routes.draw do
  resources :buyers
  resources :gas

  post '/purchase_gas' => 'gas#purchase'
  get '/reports' => 'gas#reports'

  root to: "gas#dashboard"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
	has_many :purchase_histories, :dependent => :destroy

	validates_presence_of :name
	
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  before_action :set_buyer, only: %i[ show edit update destroy ]
  before_action :get_loyalty_cards, only: %i[ new edit create ]  

  # GET /buyers or /buyers.json
  def index
    @buyers = Buyer.all
  end

  # GET /buyers/1 or /buyers/1.json
  def show
  end

  # GET /buyers/new
  def new
    @buyer = Buyer.new
  end

  # GET /buyers/1/edit
  def edit
  end

  # POST /buyers or /buyers.json
  def create
    @buyer = Buyer.new(buyer_params)

    respond_to do |format|
      if @buyer.save
        format.html { redirect_to buyer_url(@buyer), notice: "Buyer was successfully created." }
        format.json { render :show, status: :created, location: @buyer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buyers/1 or /buyers/1.json
  def update
    respond_to do |format|
      if @buyer.update(buyer_params)
        format.html { redirect_to buyer_url(@buyer), notice: "Buyer was successfully updated." }
        format.json { render :show, status: :ok, location: @buyer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buyers/1 or /buyers/1.json
  def destroy
    @buyer.destroy

    respond_to do |format|
      format.html { redirect_to buyers_url, notice: "Buyer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buyer
      @buyer = Buyer.find(params[:id])
    end

    def get_loyalty_cards
      @loyalty_card = Gas.loyalty_cards
    end

    # Only allow a list of trusted parameters through.
    def buyer_params
      params.require(:buyer).permit(:name, :loyalty_card)
    end
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/views/buyers/_form.html.erb
<div class="container">
  <%= form_with(model: buyer, local: true) do |form| %>
    <% if buyer.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(buyer.errors.count, "error") %> prohibited this buyer from being saved:</h2>

        <ul>
        <% buyer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, id: :buyer_name %>
    </div>

    <div class="field loyalty_cards">
      <%= form.label :loyalty_card %><br />

      <%= form.radio_button :loyalty_card,  "", id: "buyer_loyalty_card" %>
      <%= form.label :loyalty_card, "None"  %><br />

      <% @loyalty_card.each_with_index do |loyalty_card, index| %>
        <%= form.radio_button :loyalty_card, loyalty_card, id: "buyer_loyalty_card_#{index}" %>
        <%= form.label :loyalty_card, loyalty_card, :value => index  %><br />
      <%end%>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

</div>

app/views/buyers/edit.html.erb
<h1>Editing Buyer with ID: <%=@buyer.id%></h1>

<%= render 'form', buyer: @buyer %>

<%= link_to '❮ Back', buyers_path, class: "button" %>

app/views/buyers/index.html.erb
<div style="display: flex; justify-content: space-between; align-items: baseline;">
  <h1>Buyers</h1>
  <%= link_to '❮ Dashboard', root_path, class: "button" %>
</div>

<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Loyalty Card</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @buyers.each do |buyer| %>
      <tr>
        <td><%= buyer.name %></td>
        <td><%= buyer.loyalty_card.present? ? buyer.loyalty_card : "None"  %></td>
        <td><%= link_to 'Show', buyer %></td>
        <td><%= link_to 'Edit', edit_buyer_path(buyer) %></td>
        <td><%= link_to 'Delete', buyer, method: :delete, data: { confirm: "Are you sure you want to delete #{buyer.name}?\nThis will also delete all purchase history for this record." } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '+ New Buyer', new_buyer_path, class: "button" %>

app/views/buyers/new.html.erb
<h1>New Buyer</h1>

<%= render 'form', buyer: @buyer %>

<%= link_to '❮ Back', buyers_path, class: "button" %>

app/views/buyers/show.html.erb
<h1>Buyer with ID: <%=@buyer.id%></h1>

<p id="notice"><%= notice %></p>

<div class="container">
  <div class="field">
    <%= label_tag :name %>
    <%= text_field_tag :name, @buyer.name, disabled: true %>
  </div>

  <div class="field">
    <%= label_tag :loyalty_card %>
    <%= text_field_tag :loyalty_card, @buyer.loyalty_card, disabled: true %>
  </div>

  <%= link_to 'Edit', edit_buyer_path(@buyer), class: "button" %>
</div>

<%= link_to '❮ Back', buyers_path, class: "button" %>